dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: jx-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: jx-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: jx-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
